"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-20)eo)br0o#djiv%vt3np(k@_0x%jrtkh7!i7-b(g&sk$w2@zs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'reservation',  # 내 예약 앱 추가
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: gunicorn 환경에서도 정적 파일(admin CSS 등)을 직접 서빙.
    # 반드시 SecurityMiddleware 바로 다음에 위치해야 함.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# collectstatic이 모든 정적 파일(admin CSS 포함)을 모아둘 폴더.
# 배포 시 `python manage.py collectstatic` 실행 결과가 여기에 쌓이고,
# WhiteNoise가 이 폴더를 gunicorn에서 직접 서빙한다.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise 압축 서빙(gzip/brotli). Manifest 방식은 아직 존재하지 않는
# 이미지 파일을 {% static %}으로 참조할 때 오류가 나므로 사용하지 않는다.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# =========================================================================
# 예약 10분 전 안내 문자(SMS) 기능 설정
# =========================================================================

# 스케줄러 자동 시작 여부. 배포(Render)에서는 켜고, 로컬에서 끄고 싶으면
# 환경변수 SCHEDULER_AUTOSTART=False 로 두면 된다. 기본값은 켜짐(True).
SCHEDULER_AUTOSTART = os.environ.get('SCHEDULER_AUTOSTART', 'True') == 'True'

# --- 알리고(Aligo) 문자 API 인증정보 ---
# 보안을 위해 코드에 직접 쓰지 않고 Render 대시보드의 Environment(환경변수)에 넣는다.
# 로컬 테스트 시에는 값이 비어 있어도 앱은 정상 동작하며, 발송만 실패한다.
ALIGO_API_KEY = os.environ.get('ALIGO_API_KEY', '')   # 알리고 API Key
ALIGO_USER_ID = os.environ.get('ALIGO_USER_ID', '')   # 알리고 로그인 아이디
ALIGO_SENDER = os.environ.get('ALIGO_SENDER', '')     # 사전 등록한 발신번호(내 번호)

# 실제 발송/과금 없이 연동만 점검하려면 환경변수 ALIGO_TEST_MODE=True 로 설정.
ALIGO_TEST_MODE = os.environ.get('ALIGO_TEST_MODE', 'False') == 'True'

# 외부 크론(cron-job.org 등)이 안내 문자 엔드포인트를 호출할 때 쓰는 비밀 토큰.
# 아무나 호출하지 못하도록 막는 용도. 환경변수로 임의의 긴 문자열을 넣어두면 된다.
CRON_SECRET_TOKEN = os.environ.get('CRON_SECRET_TOKEN', '')