# Generated by Django 6.0.6 on 2026-07-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_datetime', models.DateTimeField(verbose_name='예약 날짜 및 시간')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=2, verbose_name='성별')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('user_type', models.CharField(choices=[('interior', '인테리어 업체'), ('owner', '건축주'), ('student', '학생'), ('etc', '기타')], max_length=20, verbose_name='고객 유형')),
                ('taste_results', models.TextField(verbose_name='공간 취향 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 일시')),
            ],
        ),
    ]
