# Generated by Django 6.0.6 on 2026-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='건축 계획 단계'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업체 이름'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='other_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='기타 상세 사유'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_type',
            field=models.CharField(choices=[('interior', '인테리어 업체'), ('owner', '건축주'), ('etc', '기타')], max_length=20, verbose_name='고객 유형'),
        ),
    ]
